-- MySQL Script generated by MySQL Workbench
-- ven. 20 janv. 2017 11:33:20 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `idautor` INT NOT NULL AUTO_INCREMENT,
  `autor_first_name` VARCHAR(45) NULL,
  `autor_last_name` VARCHAR(45) NULL,
  `autor_birth_date` DATE NULL,
  `autor_death_date` DATE NULL,
  `autor_presentation` LONGTEXT NULL,
  `writed_books_id` INT NULL,
  PRIMARY KEY (`idautor`),
  UNIQUE INDEX `idautor_UNIQUE` (`idautor` ASC),
  INDEX `fk_autor_1_idx` (`writed_books_id` ASC),
  CONSTRAINT `fk_autor_1`
    FOREIGN KEY (`writed_books_id`)
    REFERENCES `mydb`.`books` (`idbooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editor` (
  `ideditor` INT NOT NULL AUTO_INCREMENT,
  `editor_name` VARCHAR(45) NULL,
  `edited_books_id` INT NULL,
  PRIMARY KEY (`ideditor`),
  UNIQUE INDEX `ideditor_UNIQUE` (`ideditor` ASC),
  INDEX `fk_editor_1_idx` (`edited_books_id` ASC),
  CONSTRAINT `fk_editor_1`
    FOREIGN KEY (`edited_books_id`)
    REFERENCES `mydb`.`books` (`idbooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `idbooks` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(45) NOT NULL,
  `book_type` VARCHAR(45) NULL,
  `book_partution_date` VARCHAR(45) NOT NULL,
  `book_autor_id` INT NOT NULL,
  `book_editor_id` INT NOT NULL,
  `book_abstract` MEDIUMTEXT NULL,
  `book_cover` VARCHAR(45) NULL,
  `number_pages` INT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`idbooks`),
  UNIQUE INDEX `idbooks_UNIQUE` (`idbooks` ASC),
  INDEX `fk_books_1_idx` (`book_autor_id` ASC),
  INDEX `fk_books_2_idx` (`book_editor_id` ASC),
  CONSTRAINT `fk_books_1`
    FOREIGN KEY (`book_autor_id`)
    REFERENCES `mydb`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_2`
    FOREIGN KEY (`book_editor_id`)
    REFERENCES `mydb`.`editor` (`ideditor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_first_name` VARCHAR(45) NOT NULL,
  `user_lasrt_name` VARCHAR(45) NOT NULL,
  `user_birth_date` DATE NOT NULL,
  `user_civility` CHAR NULL,
  `favourite_type` VARCHAR(45) NULL,
  `favourite_collection` VARCHAR(45) NULL,
  `favourite_book_id` INT NULL,
  `user_pdp` VARCHAR(100) NULL,
  `user_adress` VARCHAR(45) NULL,
  `user_mail` VARCHAR(45) NOT NULL,
  `user_city` VARCHAR(45) NULL,
  `user_postal_code` VARCHAR(45) NULL,
  `user_phone_number` VARCHAR(20) NULL,
  `user_presentation` LONGTEXT NULL,
  `Last_connexion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `inscription_date` DATE NOT NULL,
  `book_id` INT NULL,
  `user_passw` VARCHAR(45) NOT NULL,
  `user_Connexion_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  UNIQUE INDEX `user_mail_UNIQUE` (`user_mail` ASC),
  INDEX `fk_user_1_idx` (`book_id` ASC),
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`books` (`idbooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
